// Generated by CoffeeScript 2.0.3
var heroes;

heroes = [
  {
    name: "Boe",
    hp: 20,
    maxHp: 20,
    woundHp: 0,
    strength: 10,
    level: 1,
    skills: [cut,
  slash]
  },
  {
    name: "Ree",
    hp: 18,
    maxHp: 18,
    woundHp: 0,
    strength: 10,
    level: 1
  },
  {
    name: "Lim",
    hp: 12,
    maxHp: 12,
    woundHp: 0,
    strength: 10,
    level: 1
  },
  {
    name: "Gar",
    hp: 24,
    maxHp: 24,
    woundHp: 0,
    strength: 10,
    level: 1
  },
  {
    name: "Foe",
    hp: 22,
    maxHp: 22,
    woundHp: 0,
    strength: 10,
    level: 1
  }
];
