// Generated by CoffeeScript 2.0.3
var bosses, monsters;

monsters = [];

bosses = [
  {
    name: "Orgus",
    sprite: "sprites/3920-20Goddess20FF6.gif",
    hp: 100,
    strength: 12,
    intelligence: 5,
    dexterity: 10,
    level: 1,
    actions: [[cut,
  slash,
  burn],
  [cut,
  slash,
  tangle],
  [cut,
  nova]]
  }
];
