// Generated by CoffeeScript 2.0.3
var clearKeysPressed, key, mouse, setupKeys;

key = {
  press: [],
  down: [],
  up: []
};

mouse = {
  press: [],
  down: [],
  up: [],
  position: {
    x: 0,
    y: 0
  },
  move: {
    x: 0,
    y: 0
  }
};

setupKeys = function(canvas) {
  document.addEventListener("keydown", function(event) {
    if (!key.press[event.keyCode]) {
      key.press[event.keyCode] = true;
    }
    return key.down[event.keyCode] = true;
  });
  document.addEventListener("keyup", function(event) {
    return key.down[event.keyCode] = false;
  });
  document.addEventListener("blur", function(event) {
    return key.down.length = 0;
  });
  canvas.addEventListener("mousedown", function(event) {
    if (!mouse.press[event.button]) {
      mouse.press[event.button] = true;
    }
    mouse.down[event.button] = true;
    if (event.target.setCapture) {
      event.target.setCapture();
    }
    return event.preventDefault();
  });
  canvas.addEventListener("mouseup", function(event) {
    mouse.down[event.button] = false;
    event.preventDefault();
    return false;
  });
  canvas.addEventListener("mousemove", function(event) {
    mouse.position.x = event.clientX;
    mouse.position.y = event.clientY;
    mouse.move.x += event.movementX || event.mozMovementX || event.webkitMovementX || 0;
    return mouse.move.y += event.movementY || event.mozMovementY || event.webkitMovementY || 0;
  });
  return canvas.addEventListener("contextmenu", function(event) {
    return event.preventDefault();
  });
};

clearKeysPressed = function() {
  var b, k;
  for (k in key.press) {
    key.press[k] = false;
  }
  for (b in mouse.press) {
    mouse.press[b] = false;
  }
  mouse.move.x = 0;
  return mouse.move.y = 0;
};
