// Generated by CoffeeScript 2.0.3
var burn, cut, nova, slash, tangle;

cut = {
  name: "Cut",
  cost: 0,
  risk: 15,
  effect: hit
};

slash = {
  name: "Slash",
  cost: 0,
  risk: 20,
  critical: 0.3,
  effect: hit
};

tangle = {
  name: "Tangle",
  cost: 0,
  risk: 15,
  effect: hit
};

burn = {
  name: "Burn",
  cost: 0,
  risk: 15,
  effect: hit
};

nova = {
  name: "Nova",
  cost: 0,
  risk: 15,
  effect: hit
};
